WIP ci+README

diff --git a/.github/workflows/android.yml b/.github/workflows/android.yml
--- a/.github/workflows/android.yml
+++ b/.github/workflows/android.yml
@@ -89,6 +89,14 @@ jobs:
           #     Your current JDK is located in  /usr/lib/jvm/temurin-8-jdk-amd64/jre
           # TODO use Java 17(LTS)
           java-version: 11.0
+      - name: DEBUG cat /home/runner/.m2/settings.xml
+        run: cat /home/runner/.m2/settings.xml || echo "nothing here!"
+        shell: bash
+      - name: update LD_LIBRARY_PATH for Rust+Java
+        # careful with this "find"; usually in CI there are multiple versions installed
+        # so DO NOT find in "/usr/lib/jvm" but use JAVA_HOME instead!
+        # -> FAIL: no libjvm.so in JAVA_HOME?? [in CI: JAVA_HOME=/opt/hostedtoolcache/Java_Temurin-Hotspot_jdk/11.0.18-10/x64]
+        run: echo "LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$(find /usr/lib/jvm -type f -name libjvm.so -regex '\(.*11.*\)' -printf "%h:")" >> $GITHUB_ENV
 
       - uses: Interstellar-Network/gh-actions/rust-build-and-test@v3-dev
         with:
@@ -184,6 +192,11 @@ jobs:
           #     Your current JDK is located in  /usr/lib/jvm/temurin-8-jdk-amd64/jre
           # TODO use Java 17(LTS)
           java-version: 11.0
+      - name: update LD_LIBRARY_PATH for Rust+Java
+        # careful with this "find"; usually in CI there are multiple versions installed
+        # so DO NOT find in "/usr/lib/jvm" but use JAVA_HOME instead!
+        # -> FAIL: no libjvm.so in JAVA_HOME?? [in CI: JAVA_HOME=/opt/hostedtoolcache/Java_Temurin-Hotspot_jdk/11.0.18-10/x64]
+        run: echo "LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$(find /usr/lib/jvm -type f -name libjvm.so -regex '\(.*11.*\)' -printf "%h:")" >> $GITHUB_ENV
 
       # TODO apparently this is not cached?
       # if not: cache the whole "Setup Android SDK"+"Delete old NDK v23"+"Install NDK v24"
