WIP ci

diff --git a/.github/workflows/android.yml b/.github/workflows/android.yml
--- a/.github/workflows/android.yml
+++ b/.github/workflows/android.yml
@@ -4,8 +4,9 @@ on:
   push:
 
 jobs:
-  # TODO split test and lint; but that REQUIRE caching else recompile from scratch in between
-  rust:
+  ##########################################################################
+  ##########################################################################
+  rust_lint:
     runs-on: ubuntu-latest
     steps:
       # install build dependencies
@@ -23,29 +24,28 @@ jobs:
           # ignore the nightly, and use stable for tests and linters
           use_toolchain_toml: false
           toolchain_components: "rustfmt,clippy"
+          working-directory: shared/rust
 
       - uses: Interstellar-Network/gh-actions/install-protoc@v3-dev
 
       ##########################################################################
-
       - uses: Interstellar-Network/gh-actions/rust-lint@v3-dev
         with:
-          working-directory: shared/rust/
-
-      - uses: Interstellar-Network/gh-actions/rust-build-and-test@v3-dev
+          working-directory: shared/rust
 
         # TODO move into separate action? ideally into a JS action "post" that setup ccache?
         # NOTE: remove if using "rust-build-and-test"
       - name: Print ccache/sccache stats
         # display stats even if tests failed
-        if: always()
+        if: success() || failure()
         run: |
           ccache --show-stats || true
           sccache --show-stats || true
         shell: bash
 
-  # TODO split test and lint; but that REQUIRE caching else recompile from scratch in between
-  android:
+  ##########################################################################
+  ##########################################################################
+  rust_test:
     runs-on: ubuntu-latest
     steps:
       # install build dependencies
@@ -60,15 +60,86 @@ jobs:
 
       - uses: Interstellar-Network/gh-actions/prepare_rust@v3-dev
         with:
+          # ignore the nightly, and use stable for tests and linters
+          use_toolchain_toml: false
+          toolchain_components: "rustfmt,clippy"
+          working-directory: shared/rust
+
+      - uses: Interstellar-Network/gh-actions/install-protoc@v3-dev
+
+      ##########################################################################
+      - uses: Interstellar-Network/gh-actions/rust-build-and-test@v3-dev
+        with:
+          working-directory: shared/rust
+
+        # TODO move into separate action? ideally into a JS action "post" that setup ccache?
+        # NOTE: remove if using "rust-build-and-test"
+      - name: Print ccache/sccache stats
+        # display stats even if tests failed
+        if: success() || failure()
+        run: |
+          ccache --show-stats || true
+          sccache --show-stats || true
+        shell: bash
+
+  ##########################################################################
+  ##########################################################################
+  android:
+    runs-on: ubuntu-latest
+    strategy:
+      matrix:
+        # cf https://stackoverflow.com/questions/66025220/paired-values-in-github-actions-matrix
+        # list of pairs:
+        # - cargo target
+        # - gradle_task: eg "assembleXXXRelease"
+        # - experimental: a flag passed to "continue-on-error"
+        # NOT GET the gradle targets with eg `./gradlew --no-daemon tasks | grep assemble`
+        android-target: [
+            {
+              cargo_target: "aarch64-linux-android",
+              gradle_task: "assembleArm64Release",
+              apk_artifact_name: "apk-Arm64Release",
+              experimental: false,
+            },
+            {
+              cargo_target: "armv7-linux-androideabi",
+              gradle_task: "assembleArmv7Release",
+              apk_artifact_name: "apk-Armv7Release",
+              # TODO? it (was supposed to fail, cf `lib-garble-rs)` b/c of pointer size difference, at least in Scuttlebut
+              # but as we are still not in PROD/GA, we only care about aarch64 for now
+              experimental: true,
+            },
+            {
+              cargo_target: "x86_64-linux-android",
+              gradle_task: "assembleX86_64Debug",
+              apk_artifact_name: "apk-X86_64Debug",
+              experimental: false,
+            },
+          ]
+    steps:
+      # install build dependencies
+      # MUST match the same step in Dockerfile
+      # - name: Install dependencies
+      #   run: sudo apt-get update && sudo apt-get install -y libboost-dev
+
+      - uses: Interstellar-Network/gh-actions/prepare@v3-dev
+        with:
+          ssh_key_input: ${{ secrets.SSH_KEY_MACHINE_USER_INTERSTELLAR_CI }}
+          install_cmake_and_ninja: true
+
+      - uses: Interstellar-Network/gh-actions/prepare_rust@v3-dev
+        with:
           use_toolchain_toml: "true"
+          toolchain_toml_path: ${{ github.workspace }}/rust-toolchain.toml
           toolchain_components: ""
+          working-directory: shared/rust
 
       - uses: Interstellar-Network/gh-actions/install-protoc@v3-dev
 
       ##########################################################################
       # cf https://github.com/android-actions/setup-android
 
-      - run: rustup target add armv7-linux-androideabi aarch64-linux-android x86_64-unknown-linux-gnu
+      - run: rustup target add ${{ matrix.android-target.cargo_target }}
 
       # https://github.com/actions/setup-java
       # TODO cache: "/home/runner/.konan"?
@@ -105,15 +176,16 @@ jobs:
         run: sdkmanager "ndk;25.1.8937393"
 
       - name: Build Wallet-App
-        # TODO build arm7, and Release only?
-        # GET the targets with eg `./gradlew --no-daemon tasks | grep assemble`
-        run: ./gradlew --no-daemon assembleArm64Release assembleX86_64Debug
+        run: ./gradlew --no-daemon ${{ matrix.android-target.gradle_task }}
+        # TODO it fails b/c of pointer size difference, at least in Scuttlebut
+        # but as we are still not in PROD/GA, we only care about aarch64 for now
+        continue-on-error: ${{ matrix.android-target.experimental }}
 
         # TODO move into separate action? ideally into a JS action "post" that setup ccache?
         # NOTE: remove if using "rust-build-and-test"
       - name: Print ccache/sccache stats
         # display stats even if tests failed
-        if: always()
+        if: success() || failure()
         run: |
           ccache --show-stats || true
           sccache --show-stats || true
@@ -123,6 +195,6 @@ jobs:
       - name: Upload APKs
         uses: actions/upload-artifact@v3
         with:
-          name: all-apks
-          path: |
-            ./androidApp/build/outputs/apk/arm64/release/androidApp-*.apk
+          name: ${{ matrix.android-target.apk_artifact_name }}
+          path: ./androidApp/build/outputs/apk/**/**/*.apk
+          retention-days: 7
